name: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install zip
        run: sudo apt-get install zip -y

      - name: Build
        run: |
          pnpm tsc && vite build # The build command of your project

      - name: Create zip file
        run: zip -r dist.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.zip

      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          script: |
            unzip -o dist.zip -d /public_html
